Document that :func:`trio.sleep_forever` is guaranteed to raise an exception now.
